ci:
  autoupdate_schedule: 'monthly'
  autofix_prs: true

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.10
  hooks:
    # Run the linter with fix argument.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [--fix]  # This will enable automatic fixing of lint issues where possible.
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # Use the ref you want to point at
  hooks:
    - id: trailing-whitespace
    - id: check-toml
    - id: check-yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      args: [
        "--ignore-words",
        ".codespellignore",
        "--ignore-regex",
        "[A-Za-z0-9+/]{100,}",
      ]